### ISSUE TITLE
support for consul with ACL

### ISSUE THREAD

**Issue by naveennooney** [marcosbarbero/spring-cloud-zuul-ratelimit#134]
Using CONSUL, i got the below error .. it seems to be not using ACL Token while retrieving key.
Do you support ACL configuration to use with CONSUL? Or did I miss something?

com.ecwid.consul.transport.TransportException: org.apache.http.client.ClientProtocolException
        at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:77)
        at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:34)
        at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:128)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValue(KeyValueConsulClient.java:73)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValue(KeyValueConsulClient.java:67)
        at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValue(KeyValueConsulClient.java:57)
        at com.ecwid.consul.v1.ConsulClient.getKVValue(ConsulClient.java:452)
        at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.ConsulRateLimiter.getRate(ConsulRateLimiter.java:52)
        at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.AbstractRateLimiter.create(AbstractRateLimiter.java:59)

**Comment by marcosbarbero** [comment]
Hello @naveennooney our support for consul rely on `spring-cloud-consul` and AFAIK they do support token ACLs.
