### ISSUE TITLE
NPE in DefaultRateLimitKeyGenerator

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#28]
In the case that someone tries to access a url without a route, NPE is thrown.
This is because it tries to get the id and the path from the route

```
Caused by: java.lang.NullPointerException: null
	at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.DefaultRateLimitKeyGenerator.key(DefaultRateLimitKeyGenerator.java:46)
	at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.filters.RateLimitPreFilter.lambda$run$0(RateLimitPreFilter.java:76)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.filters.RateLimitPreFilter.run(RateLimitPreFilter.java:75)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
```

**Comment by lchayoun** [comment]
@marcosbarbero can you release a version with this fix please?

**Comment by marcosbarbero** [comment]
@lchayoun will do it today

**Comment by marcosbarbero** [comment]
@lchayoun already available on maven central [v1.3.4.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v1.3.4.RELEASE)

**Comment by lchayoun** [comment]
@marcosbarbero spring-cloud-zuul-ratelimit-dependencies is not published
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.marcosbarbero.cloud%22%20AND%20a%3A%22spring-cloud-zuul-ratelimit-dependencies%22

**Comment by marcosbarbero** [comment]
@lchayoun weird, I checked it while uploading.
I'm doing it again now, let's see. Did you notice any other missing dependency?

**Comment by marcosbarbero** [comment]
@lchayoun it seems to be [available now](https://search.maven.org/#artifactdetails%7Ccom.marcosbarbero.cloud%7Cspring-cloud-zuul-ratelimit-dependencies%7C1.3.4.RELEASE%7Cpom)

**Comment by lchayoun** [comment]
@marcosbarbero working, thanks!
