### ISSUE TITLE
Further customization problem

### ISSUE THREAD

**Issue by loraclaa** [marcosbarbero/spring-cloud-zuul-ratelimit#43]
Further customization mentioned a bean injected to override RateLimitKeyGenerator.
I override the RateLimitKeyGenerator in Spring boot Application but got build errors.

```
 @Bean
    public RateLimitKeyGenerator rateLimitKeyGenerator(final RateLimitProperties properties) {
        return new DefaultRateLimitKeyGenerator(properties) {
            @Override
            public String key(HttpServletRequest request, Route route, RateLimitProperties.Policy policy) {
                String key = customkey(request, route, policy) + ":" + request.getMethod();
                return key;
            }

            public String customkey(final HttpServletRequest request, final Route route, final Policy policy) {
                final List<Type> types = policy.getType();
                final StringJoiner joiner = new StringJoiner(":");
                joiner.add(properties.getKeyPrefix());
                if (route != null) {
                    joiner.add(route.getId());
                }
                if (!types.isEmpty()) {
                    if (types.contains(Type.URL) && route != null) {
                        // joiner.add(route.getPath());
                        // updated for full path + domain
                        joiner.add(route.getFullPath());
                    }
                    if (types.contains(Type.ORIGIN)) {
                        joiner.add(this.getRemoteAddress(request));
                    }
                    if (types.contains(Type.USER)) {
                        // joiner.add(request.getRemoteUser() != null ? request.getRemoteUser() :
                        // "ANONYMOUS_USER");
                        // updated for sid and token
                        String value = null;
                        Cookie[] cookies = request.getCookies();
                        if ((null != cookies) || (cookies.length != 0)) {
                            for (Cookie cookie : cookies) {
                                if (cookie.getName().equalsIgnoreCase(ConstantsBean.SID)) {
                                    value = cookie.getValue();
                                }
                            }
                        }
                        joiner.add(value);
                    }
                }
                return joiner.toString();
            }

            private String getRemoteAddress(final HttpServletRequest request) {
                String xForwardedFor = request.getHeader(X_FORWARDED_FOR_HEADER);
                if (properties.isBehindProxy() && xForwardedFor != null) {
                    return xForwardedFor;
                }
                return request.getRemoteAddr();
            }
        };
    }
```
maven install got following:

```
Description:

Parameter 0 of method rateLimitKeyGenerator in com.wanda.cloud.bss.apigw.ApiGatewayApplication required a bean of type 'com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties' that could not be found.


Action:

Consider defining a bean of type 'com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties' in your configuration.

2017-12-06 18:35:09.185 ERROR 8364 --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@2a32de6c] to prepare test instance [com.wanda.cloud.bss.apigw.ApiGatewayApplicationTests@4cc7d00d]

java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83) ~[spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189) ~[spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131) ~[spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230) ~[spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191) [spring-test-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
```

Any suggestions that if the injection has any problem

**Comment by lchayoun** [comment]
@loraclaa did you enable rate limit?
```yml
zuul:
  ratelimit:
    enabled: true 
```

**Comment by loraclaa** [comment]
@lchayoun I did. What i want more is the further customization to my own business, and i need to overwrite -user and -url two parts in keygenerator.

**Comment by marcosbarbero** [comment]
@loraclaa do you have a shareable project that reproduces the problem?

**Comment by loraclaa** [comment]
@marcosbarbero It's a internal project which belongs to company, I can only paste parts of the codes.
I inject the @Bean in the my application class like below:
@SpringBootApplication
@EnableZuulProxy
@EnableScheduling
@EnableCircuitBreaker
@EnableHystrixDashboard
public class ApiGatewayApplication{.....
@Bean
public RateLimitKeyGenerator rateLimitKeyGenerator(final RateLimitProperties  * properties) { 
    return new DefaultRateLimitKeyGenerator(properties) {...

Is it the right place or should it be injected in the defined filter?

Thanks.

**Comment by lchayoun** [comment]
@loraclaa try to create the bean in a dedicated @Configuration class

**Comment by loraclaa** [comment]
@lchayoun Thank you, it works, exception is finished with also @Primary annotation. Or it will lead to some other exception with suggest "Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed".
I will check if my customization works.

**Comment by lchayoun** [comment]
great 👍
