### ISSUE TITLE
JPA uses MySQL reserved `KEY` keyword

### ISSUE THREAD

**Issue by immno** [marcosbarbero/spring-cloud-zuul-ratelimit#50]
```java
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar(255) not null, expiration datetime, remaining bigint, remaining_quota bi' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_101]
```

I know the reason, because of the use of the MySQL keyword key.
I revise as follows:
```bash
create table rate (key2 varchar(255) not null, expiration datetime, remaining bigint, remaining_quota bigint, reset bigint, primary key (key2))
```
It can run.
I use MySql version 5.7.20.
![image](https://user-images.githubusercontent.com/10646884/35325807-c712df2c-012f-11e8-8f42-58c154360869.png)

[MySQL Keywords reference](https://dev.mysql.com/doc/refman/5.7/en/keywords.html)

**Comment by marcosbarbero** [comment]
@immno nice catch!
